# Generated by Django 4.2.4 on 2023-08-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_gpsdata_altitude_alter_gpsdata_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsdata',
            name='altitude',
            field=models.DecimalField(decimal_places=8, max_digits=9),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=9),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=9),
        ),
    ]
