# Generated by Django 4.2.4 on 2023-08-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_gpsdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsdata',
            name='altitude',
            field=models.DecimalField(decimal_places=12, max_digits=14),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='latitude',
            field=models.DecimalField(decimal_places=12, max_digits=14),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='longitude',
            field=models.DecimalField(decimal_places=12, max_digits=14),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='speed',
            field=models.DecimalField(decimal_places=14, max_digits=14),
        ),
    ]
