# Generated by Django 4.2.4 on 2023-08-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_gpsdata_altitude_alter_gpsdata_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsdata',
            name='speed',
            field=models.DecimalField(decimal_places=9, max_digits=14),
        ),
    ]
