# Generated by Django 4.2.4 on 2023-09-03 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_locationdata_delete_gpsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='base.locationdata'),
        ),
    ]
